### PR TITLE
modifying to module intel/2022a

### PR DESCRIPTION
**Pull request by monsieuralok**
[ Description of the changes in this Pull Request. It should be enough
information for someone not following this development to understand.
Lines should be wrapped at about 72 characters. Please also update
the CIME documentation, if necessary, in doc/source/rst and indicate
below if you need to have the gh-pages html regenerated.]

Test suite:
Test baseline:
Test namelist changes:
Test status: [bit for bit, roundoff, climate changing]

Fixes [CIME Github issue #]

User interface changes?:

Update gh-pages html (Y/N)?:

### CODE REVIEW

**Review by TomasTorsvik — APPROVED** [review]
Thanks @monsieuralok !
Does these module changes preserve bit-by-bit reproducible results compared with 2020a? Mats mentioned he had tested with 2022a, and I believe he was able to reproduce old results.

**Comment by TomasTorsvik** [comment]
Would be useful to tag the `noresm2_1_develop` branch after merging this PR. Can we use the same tag for both noresm2.1 and noresm2.3?

**Comment by monsieuralok** [comment]
> Thanks @monsieuralok ! Does these module changes preserve bit-by-bit reproducible results compared with 2020a? Mats mentioned he had tested with 2022a, and I believe he was able to reproduce old results.

I am not sure as yesterday I have not tested for 2020 Vs 2022 but, I tested earlier (in june) for 2 years ( each time executing 1 month) and on one instances it was not reproducible but on rest it was bit-wise same. @matsbn has tested only for BLOM only case as he mentioned.

**Comment by monsieuralok** [comment]
> Would be useful to tag the `noresm2_1_develop` branch after merging this PR. Can we use the same tag for both noresm2.1 and noresm2.3?

if cime is same for noresm2.1 and noresm2.3 then, we can use a single tag. I will check it.

**Comment by TomasTorsvik** [comment]
I get bit-wise identical output for NOINYOC compared with noresm2.0.7. I check out release-noresm2.0.7 and replace the cime component with the `monsieuralok:intel2022a_module` branch.

**Pull request merged**
