### PR TITLE
Include suport for separate hamocc test list

### LINKED ISSUE #92: Add support for separate iHAMOCC test list
@gold2718 , @mvertens - I would like to introduce a separate test file for iHAMOCC. To my understanding, this requires a change in the `config_files.xml` file.

### PR DESCRIPTION
**Pull request by TomasTorsvik**
This change will allow us to define a separate test list for iHAMOCC.

Test suite: None
Test baseline: None
Test namelist changes: aux_hamocc_noresm
Test status: [bit for bit, roundoff, climate changing]

Fixes [CIME Github issue #]
- #92 
- https://github.com/NorESMhub/NorESM/issues/616

User interface changes?:

Update gh-pages html (Y/N)?:

### CODE REVIEW

**Review by gold2718 — CHANGES_REQUESTED** [review]
I do not understand the need for this change. You can call your testlists anything you want inside of `<blom>/cime_config/testdefs/testlist_blom.xml`. Please explain.

**Review by mvertens — CHANGES_REQUESTED** [review]
@TomasTorsvik - what you want to do is edit testlist_blom.xml and add the new tests under a different testlist category. hamocc cannot be a new component in noresm - it is only an added configuration to blom. I'm happy to talk more about this - a chat might be very helpful.

**Comment by TomasTorsvik** [comment]
We have defined a category "aux_hamocc_noresm" in `testlist_blom.xml`. When I try to set up a test with this category, the test system does not find the `components/blom/cime_config/testdefs/testmods_dirs/hamocc/` directory. It seems, the default is either `components/pop/cime_config` or the root `cime_config`.

**Comment by TomasTorsvik** [comment]
OK, I can probably revert the change of having a separate `testmods_dirs/hamocc` back to using only `testmods_dirs/blom`.

**Comment by TomasTorsvik** [comment]
@mvertens , @gold2718 - I see you commented on the NorESM issue. I will close this one.

**Pull request closed without merging**
