### PR TITLE
ocn_surface_flux_scheme=1 by default for NorESM compsets

### PR DESCRIPTION
**Pull request by DirkOlivie**
Introduced modification to have for NorESM compsets by default ocn_surface_flux_scheme=1 (COARE flux) instead of 0 (standard for CESM compsets) in NorESM2.2.

In the upgraded CESM2.2 version which is the basis for NorESM2.2, ocn_surface_flux_scheme has been introduced, but its default value is 0.  By this modification, the value will be 1 for NorESM compsets.

The results are equal (bit-identical) to putting in user_nl_cpl : ocn_surface_flux_scheme = 1

Modified files : 
src/drivers/mct/cime_config/buildnml
src/drivers/mct/cime_config/config_component_cesm.xml
src/drivers/mct/cime_config/namelist_definition_drv.xml

Test suite: N1850_f19_tn14_20211104_test22
Test baseline: N1850_f19_tn14_20211104_test16
Test namelist changes: 
Test status: bit for bit

Fixes [CIME Github issue #]

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Review by monsieuralok — APPROVED** [review]

**Comment by mvertens** [comment]
@tto061 - should this be implemented in the noresm2.3 development code right now.
I'm happy to put this in for the making waves project.

**Comment by tto061** [comment]
Hi Mariana

this option works in cmeps out-of-the-box, so just specifying the 
namelist variable ocn_surface_flux_scheme in user_nl_cpl is sufficient.

Background: it's been taken from NorESM and put into E3SM, and as a 
result ended up in ESCOMP a while ago, and thence into cmeps. The 
acknowledgment in shr_flux_mod.F90 say "Jack Reeves Eyre (UA) and Kai 
Zhang (PNNL) added COARE/Fairall surface flux scheme option [...] based 
on code from Thomas Toniazzo", but in fact they copied my code wholesale 
without changes (and only added the last bit with my name upon my 
insistence).

So no need to do anything :)

Cheers
Thomas

Thomas Toniazzo
MISU          Stockholms university
SE-106 91 Stockholm         Sverige

**Comment by mvertens** [comment]
@DirkOlivie - this never got incorporated into CIME and for noresm2.5 and later this code is in cmeps and not in cime.
How do you want to proceed? Also - since cesm2.2 is not really being used - should this PR be closed?

**Comment by mvertens** [comment]
@DirkOlivie - what is the status of this for cesm2.1.

**Comment by DirkOlivie** [comment]
I think this became relevant in noresm2.2 because noresm2.2 has some more recent CAM-version (in which this modification was required) than noresm2.0 and noresm2.1.  So it is not needed in noresm2.1.

**Comment by gold2718** [comment]
Per @DirkOlivie above, this PR is no longer necessary.

**Pull request closed without merging**
